#!/bin/bash
# ─────────────────────────────────────────────────
# SKAPARA Coming Soon — Build Script
# Reads .env and generates config.js
# ─────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

if [ ! -f "$ENV_FILE" ]; then
  echo "ERROR: .env not found. Copy .env.example to .env and fill in your values."
  exit 1
fi

# Source .env (handle quotes and whitespace)
while IFS='=' read -r key value; do
  # Skip comments and empty lines
  [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
  # Trim whitespace
  key="$(echo "$key" | xargs)"
  value="$(echo "$value" | xargs)"
  # Remove surrounding quotes
  value="${value%\"}"
  value="${value#\"}"
  value="${value%\'}"
  value="${value#\'}"
  export "$key=$value"
done < "$ENV_FILE"

# Validate required vars
for var in SUPABASE_URL SUPABASE_ANON_KEY TURNSTILE_SITE_KEY; do
  if [ -z "${!var:-}" ] || [[ "${!var}" == *"your-"* ]]; then
    echo "ERROR: $var is not set or still has placeholder value."
    exit 1
  fi
done

# Generate config.js next to coming-soon.html
OUTPUT_DIR="$SCRIPT_DIR/../public"
cat > "$OUTPUT_DIR/config.js" << JSEOF
// Auto-generated by build.sh — DO NOT EDIT
// Re-run coming-soon/build.sh after changing .env
window.__SKAPARA = {
  supabaseUrl: "${SUPABASE_URL}",
  supabaseAnonKey: "${SUPABASE_ANON_KEY}",
  turnstileSiteKey: "${TURNSTILE_SITE_KEY}"
};
JSEOF

echo "config.js generated at public/config.js"
echo "Deploy these files to your hosting:"
echo "  - public/coming-soon.html (rename to index.html)"
echo "  - public/config.js"
