// Auto-generated by build.sh — DO NOT EDIT
// Re-run coming-soon/build.sh after changing .env
window.__SKAPARA = {
  supabaseUrl: "https://your-project.supabase.co",
  supabaseAnonKey: "your-supabase-anon-key",
  turnstileSiteKey: "0x4AAAAAAClRMrRPA3VylBNO"
};
