ALTER TABLE ai_generations
  ADD COLUMN IF NOT EXISTS confidence DECIMAL(3,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS style_preset TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS product_type TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS product_id TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seed TEXT DEFAULT NULL;
